# Generated by Django 4.2.6 on 2023-10-12 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='seat_no',
        ),
        migrations.AddField(
            model_name='ticket',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='ticket',
            name='product',
            field=models.IntegerField(choices=[(1, 'MASTERDIGIT'), (2, 'KEYLASHOP'), (3, 'GARAGEDIGIT')], null=True, verbose_name='Produit'),
        ),
        migrations.CreateModel(
            name='MessageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tickets.message')),
            ],
        ),
    ]
