# Generated by Django 4.2.6 on 2023-10-12 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_remove_ticket_seat_no_ticket_image_ticket_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='image',
        ),
    ]
