# Generated by Django 4.2.6 on 2023-10-13 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_message_image_delete_messageimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created On'),
        ),
    ]
