# Generated by Django 4.2.6 on 2023-10-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_alter_ticket_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='product',
            field=models.IntegerField(choices=[(1, 'MASTERDIGIT'), (2, 'KEYLASHOP'), (3, 'GARAGEDIGIT'), (3, 'GFS')], null=True, verbose_name='Produit'),
        ),
    ]
