# Generated by Django 4.2.6 on 2023-10-31 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_alter_ticket_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='department',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='product',
            field=models.IntegerField(choices=[(1, 'MASTERDIGIT'), (2, 'KEYLASHOP'), (3, 'GARAGEDIGIT'), (4, 'GFS')], null=True, verbose_name='Produit'),
        ),
    ]
