# Generated by Django 4.2.6 on 2023-11-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_remove_ticket_department_alter_ticket_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='owner',
            field=models.CharField(max_length=100, null=True, verbose_name='owner'),
        ),
    ]
